DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS list_items CASCADE;



CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE list_items (
  id SERIAL PRIMARY KEY NOT NULL,
  entry VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
